import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { homedir } from 'node:os'
import { join, resolve } from 'node:path'

type McpServerEntry = {
  command?: string
  args?: string[]
  env?: Record<string, string>
  url?: string
  type?: string
}

type McpConfig = { mcpServers?: Record<string, McpServerEntry> }

const CANDIDATES = [
  { path: '.mcp.json', label: 'Claude Code project config' },
  {
    path: join(homedir(), 'Library/Application Support/Claude/claude_desktop_config.json'),
    label: 'Claude Desktop config',
  },
]

export function findMcpConfig(explicit?: string): { path: string; label: string } | null {
  if (explicit) return { path: resolve(explicit), label: explicit }
  for (const c of CANDIDATES) {
    if (existsSync(c.path)) return c
  }
  return null
}

export function generateConfig(source: McpConfig): { yaml: string; servers: string[] } {
  const entries = Object.entries(source.mcpServers ?? {}).filter(
    // Don't wrap an existing toolwarden entry in itself.
    ([name]) => !name.toLowerCase().includes('toolwarden'),
  )
  if (entries.length === 0) {
    throw new Error('no MCP servers found in the source config')
  }

  const serverBlocks = entries
    .map(([name, s]) => {
      const safeName = name.replace(/[^a-zA-Z0-9_-]/g, '-')
      if (s.url) {
        return `  - name: ${safeName}\n    url: ${s.url}`
      }
      const args = (s.args ?? []).map((a) => JSON.stringify(a)).join(', ')
      const env = Object.entries(s.env ?? {})
        .map(([k, v]) => `\n      ${k}: ${JSON.stringify(v)}`)
        .join('')
      return (
        `  - name: ${safeName}\n    command: ${JSON.stringify(s.command ?? '')}\n    args: [${args}]` +
        (env ? `\n    env:${env}` : '')
      )
    })
    .join('\n')

  const yaml = `# Generated by toolwarden-gateway init. Edit the policy to taste.
policy:
  budget:
    monthly: 5.00        # 0 disables budget enforcement
    currency: USD
  limits:
    max_per_call: 0.05
    ask_above: 0.10
  rules: []              # e.g. { match: "fs:write_*", action: ask }
  default: allow

storage:
  dir: ~/.toolwarden

servers:
${serverBlocks}
`
  return { yaml, servers: entries.map(([n]) => n) }
}

export function runInit(explicitSource: string | undefined, outPath: string): void {
  const found = findMcpConfig(explicitSource)
  if (!found) {
    console.error(
      'No MCP config found. Looked for .mcp.json here and the Claude Desktop config.\n' +
        'Point at one explicitly: toolwarden-gateway init --from <path>',
    )
    process.exit(1)
  }
  if (existsSync(outPath)) {
    console.error(`${outPath} already exists, refusing to overwrite.`)
    process.exit(1)
  }

  const source = JSON.parse(readFileSync(found.path, 'utf8')) as McpConfig
  const { yaml, servers } = generateConfig(source)
  writeFileSync(outPath, yaml)

  console.log(`Wrapped ${servers.length} server(s) from ${found.label}: ${servers.join(', ')}`)
  console.log(`Wrote ${outPath}\n`)
  console.log('Now point your MCP client at the gateway instead. For Claude Code (.mcp.json):\n')
  console.log(
    JSON.stringify(
      {
        mcpServers: {
          toolwarden: {
            command: 'npx',
            args: ['-y', '@toolwarden/gateway', '--config', outPath],
          },
        },
      },
      null,
      2,
    ),
  )
  console.log(
    '\nYour tools now flow through the policy in ' +
      outPath +
      '. Receipts land in ~/.toolwarden/receipts.jsonl.',
  )
}
